### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by kosarko** [ufal/wembedding_service#7]
While preparing the dockerized version with udpipe 2.10 models; I've encountered this error:
```
#16 134.7 Traceback (most recent call last):
#16 134.7   File "start_wembeddings_server.py", line 54, in <module>
#16 134.7     wembeddings_lambda()
#16 134.7   File "start_wembeddings_server.py", line 50, in <lambda>
#16 134.7     wembeddings_lambda = lambda: wembeddings.WEmbeddings(threads=args.threads, preload_models=args.preload_models)
#16 134.7   File "/wembedding_service/wembeddings/wembeddings.py", line 93, in __init__
#16 134.7     self._models[model_name].load()
#16 134.7   File "/wembedding_service/wembeddings/wembeddings.py", line 50, in load
#16 134.7     self.tokenizer = transformers.AutoTokenizer.from_pretrained(self._transformers_model_name, use_fast=True)
#16 134.7   File "/usr/local/lib/python3.6/dist-packages/transformers/models/auto/tokenization_auto.py", line 546, in from_pretrained
#16 134.7     return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
#16 134.7   File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py", line 1787, in from_pretrained
#16 134.7     **kwargs,
#16 134.7   File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py", line 1915, in _from_pretrained
#16 134.7     tokenizer = cls(*init_inputs, **init_kwargs)
#16 134.7   File "/usr/local/lib/python3.6/dist-packages/transformers/models/xlm_roberta/tokenization_xlm_roberta_fast.py", line 149, in __init__
#16 134.7     **kwargs,
#16 134.7   File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_fast.py", line 119, in __init__
#16 134.7     "Couldn't instantiate the backend tokenizer from one of: \n"
#16 134.7 ValueError: Couldn't instantiate the backend tokenizer from one of:
#16 134.7 (1) a `tokenizers` library serialization file,
#16 134.7 (2) a slow tokenizer instance to convert or
#16 134.7 (3) an equivalent slow tokenizer class to instantiate and convert.
#16 134.7 You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
#16 ERROR: executor failed running [/bin/bash -c python start_wembeddings_server.py 8000 --preload_models=all --preload_only]: exit code: 1
```

that's solved in https://github.com/ufal/udpipe2-docker/blob/a424a1c06f05b8d04599ef603f5acb48c85bf634/wembedding/Dockerfile#L12 by installing sentencepiece. Shouldn't that be in requirements.txt?

**Comment by foxik** [comment]
Well, the UDPipe 2.10 models do not use the XLM-RoBERTa at all -- it is in the list of supported models for some experiments (and we do not want to remove it), but it should not really be part of the UDPipe 2.10 docker (it takes ~600MB unnecessarily) -- the right approach is to preload only the mBERT and RobeCzech.

Also, it seems the official `xlm-roberta-base` HF model has published the TF checkpoint and that `sentencepiece` model is no longer necessary for running the tokenizer -- I will investigate, but that means we will switch to this model anyway.

**Comment by foxik** [comment]
(Oh, XLM-RoBERTA-base is not 600MB, it is 1.8G.)

**Comment by foxik** [comment]
(Switched to new XLM-RoBERTA-base checkpoint in 073e1bf, so now the `sentencepiece` is not needed anyway.)
